# https://eslint.org/docs/rules/
env:
  browser: false
  es6: true
  node: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
rules:
  no-console: 0
  # [ ], default: "never"
  comma-dangle:
    - warn
    - only-multiline
  # [ ], default: 4
  indent:
    - error
    - 2
  # [ ], default: "before": true, "after": true
  keyword-spacing:
    - error
    - after: true
      before: true
  # [ ], default: "unix"
  linebreak-style:
    - error
    - unix
  # [ ], default: ["error", 80]
  #max-len:
  #  - warn
  #  - 80
  # [ ], default: {"skipBlankLines": false, "ignoreComments": false}
  no-trailing-spaces:
    - error
  # [x], default: none
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  # [ ], default: "double"
  quotes:
    - error
    - single
  # [ ], default: "never"
  object-curly-spacing:
    - error
    - always
  semi:
    - error
    - always
  # [ ], default: "always"
  space-before-function-paren:
    - error
    - always
